@aurorax_list_datasets
@aurorax_list_observatories
@aurorax_ucalgary_get_urls
@aurorax_ucalgary_download
@aurorax_ucalgary_readfile_asi
@aurorax_ucalgary_readfile_skymap
@aurorax_ucalgary_readfile_calibration
@aurorax_ucalgary_read
@aurorax_ucalgary_is_read_supported

@aurorax_helpers
@aurorax_requests
@aurorax_metadata_filters
@aurorax_availability
@aurorax_conjunctions
@aurorax_data_products
@aurorax_ephemeris
@aurorax_sources
@aurorax_open_externally

@aurorax
